spring.application.name=PortfolioManagement
spring.datasource.url=${{ secrets.SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/stockdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true }}
spring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME:root }}
spring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD:root }}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Use InnoDB storage engine
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

jwt.secret=${{ secrets.JWT_SECRET }}:-thisisatncproject

# Required for Springfox Swagger - use AntPathMatcher
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Reports storage configuration
app.reports.directory=./reports

# External Wallet Microservice
wallet.service.url=${{ secrets.WALLET_SERVICE_URL:http://wallet:8091 }}

app.cors.allowed-origins=${FRONTEND_ORIGINS:http://stockfolio.duckdns.org,https://stockfolio.duckdns.org,http://localhost}
