spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:mysql://prod-db-server:3306/portfolio_manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8080
  ssl:
    enabled: false

logging:
  level:
    root: INFO
    com.tnc: INFO
